# Generated by Django 5.0.7 on 2024-07-14 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand", models.CharField(max_length=100, verbose_name="bike brand")),
                ("model", models.CharField(max_length=100, verbose_name="bike brand")),
                ("year_manufacture", models.IntegerField(max_length=100, verbose_name="year of manufacture")),
                (
                    "bike_status",
                    models.CharField(
                        choices=[("AV", "Available"), ("RE", "Rented"), ("UR", "Under renovation"), ("DE", "Deleted")],
                        default="AV",
                        max_length=2,
                        verbose_name="Bike status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bike",
                "verbose_name_plural": "Bikes",
                "ordering": ["bike_status"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[(1, "Status active"), (0, "Status inactive")], default=1, verbose_name="Order status"
                    ),
                ),
                ("time_start", models.DateTimeField(auto_now_add=True, verbose_name="time start")),
                (
                    "time_rent",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(169),
                        ],
                        verbose_name="Time rent",
                    ),
                ),
                ("price_hour", models.IntegerField(verbose_name="Price hour")),
                ("total_price", models.IntegerField(verbose_name="Total price")),
                (
                    "bike_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="bicycles.bike",
                        verbose_name="Bike",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["order_status"],
            },
        ),
    ]
