# Generated by Django 5.0.7 on 2024-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="year_manufacture",
            field=models.IntegerField(verbose_name="year of manufacture"),
        ),
    ]
